### ISSUE TITLE
Empty white space when browser dimensions are in high ratios.

### ISSUE THREAD

**Issue by TropicalMango** [Ishadijcks/MooLite#70]
**Describe the bug**
An empty white space appears next to the plugin utility bar when the browser dimensions are either very wide or very tall (for example, split screening two browser windows). It appears regardless of whether one of the plugin menus is open. It is not always the same size as the menu. 

**To Reproduce**
1. Be on 'https://www.milkywayidle.com/game'
2. Snap browser window to half-screen or other weird dimensions.
3. See error

**Expected behavior**
I didn't expect to see the plugin creating empty space.

**Screenshots**
![chrome](https://user-images.githubusercontent.com/46412116/236774681-ad7363ee-a005-415b-8768-7f766b8c7bf4.PNG)
![chrome 3](https://user-images.githubusercontent.com/46412116/236774684-6217e6b6-ed1e-4c77-966f-77684886b9d8.PNG)
![firefox 3](https://user-images.githubusercontent.com/46412116/236774756-3bf75fea-2d07-4923-9264-19b3f4be6022.PNG)
![firefox](https://user-images.githubusercontent.com/46412116/236774760-5f1f65e0-f473-4879-bf53-07764a357279.PNG)

**Browser**
Chrome Version 113.0.5672.64 (Official Build) (64-bit)
Firefox 112.0.2 (64-bit)

**Additional context**
Other browser extensions do not seem to affect this bug. No other Tampermonkey scripts are installed or active.

**Comment by Ishadijcks** [comment]
Thanks for the detailed report, I can confirm this bug.

It is likely something to do with the way the Vue app is injected into the page.
Via the inspector we can probably see what exactly is causing the whitespace

**Comment by KevinLee3627** [comment]
From what I can tell, it seems like it's related to the `transform: scale(xx)` property on the `#root` style. If you change the height of the window you can see the media queries that affect this property.

![image](https://github.com/Ishadijcks/MooLite/assets/11792324/14745f17-9487-4d13-aeb6-65aef31b3c11)

If you disable the `transform: scale(xx)` properties, and set the `height` property to 100% it seems to look normal.

![image](https://github.com/Ishadijcks/MooLite/assets/11792324/afb766b0-ee52-4f93-89f5-8542db19108f)

**Comment by Ishadijcks** [comment]
Agreed. The problem is that there are many for various breakpoints.

I'm not entirely sure why they were set, so I don't feel comfortable overriding them yet
